### ISSUE TITLE
API suggestions

### ISSUE THREAD

**Issue by tomasdev** [callmecavs/heading-links.js#2]
Would be super lovely to
1. Be able to add an API method that list all elements that have been parsed.
2. Set a flag to append `<a href="#generated-id">∞</a>` on rollover or something

**Comment by callmecavs** [comment]
1. agreed. node list, or array of strings? my inclination would be towards a node list
2. agreed, will definitely add this. would like to avoid a CSS dep if possible, maybe inline styles?

**Comment by callmecavs** [comment]
@tomasdev added the hover links - would appreciate your thoughts
